### ISSUE TITLE
Rendering to .html or .md for web viewing. 

### ISSUE THREAD

**Issue by seabbs** [akira-endo/Intro-PMCMC#2]
It would be nice if the .Rmds were compiled to a format for viewing on the web.

**Comment by akira-endo** [comment]
Html files have been added.

**Comment by seabbs** [comment]
Not to be too fussy (😸) but could you either enable GitHub pages (in settings) and link to the rendered pages or output to .md so they can be read from GitHub!

**Comment by akira-endo** [comment]
Oh yes that makes sense. Now readme.md links to rendered htmls. Thanks!
