### ISSUE TITLE
pmcmcTutorial.Rmd/.html

### ISSUE THREAD

**Issue by GreyPEK** [akira-endo/Intro-PMCMC#4]
Maybe a silly question! I can run almost code in 'pmcmcTutorial.Rmd/[.html](https://akira-endo.github.io/Intro-PMCMC/pmcmcTutorial.html)', but when I run this:
```
inference_results<-RF_PMMH(simuRF$Y, PBar=F, p0=0.0001)
```
there is an error:
```
Error in if (lU < cumWj) { : missing value where TRUE/FALSE needed
```
Could you please give me some suggestion? Thank you!

**Comment by GreyPEK** [comment]
Sorry. This may be because of a problem with my computer, which is now working.

**Comment by akira-endo** [comment]
Great to hear that the issue is solved!
